### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kasia1403** [kappa-maintainer/phosphor-forge112#5]
To make Hesperus independent of mixinbooter and to make Hesperus possible to delete just by disabling phosphor. jar file instead ( I don't even know which files to delete ).

**Comment by kappa-maintainer** [comment]
Mixin without mixinbooter will potientially cause many compatibility problem, and most of 112 optimization mods requires Mixinbooter these days
Renaming jar is a good idea though
